# Generated by Django 4.0.1 on 2022-01-23 14:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_image', models.ImageField(blank=True, default='plceholder.png', null=True, upload_to="{% static 'images/")),
                ('cast_title', models.CharField(blank=True, max_length=300, null=True)),
                ('cast_type', models.CharField(blank=True, max_length=240, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InTheater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_images', models.ImageField(blank=True, default='plceholder.png', null=True, upload_to="{% static 'images/")),
                ('theater_desc', models.CharField(blank=True, max_length=300, null=True)),
                ('theater_duration', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(blank=True, max_length=300, null=True)),
                ('actor_title', models.CharField(blank=True, max_length=300, null=True)),
                ('actor_images', models.ImageField(blank=True, default='plceholder.png', null=True, upload_to="{% static 'images/")),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_slider', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='plceholder.png', null=True, upload_to="{% static 'images/")),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(blank=True, max_length=300, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('writter', models.CharField(blank=True, max_length=400, null=True)),
                ('director', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('run_time', models.CharField(blank=True, max_length=250, null=True)),
                ('mmpa_rating', models.CharField(blank=True, max_length=250, null=True)),
                ('plote_words', models.CharField(blank=True, max_length=200, null=True)),
                ('genres', models.ManyToManyField(blank=True, null=True, to='movieview.Genres')),
            ],
        ),
        migrations.CreateModel(
            name='MovieLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars_name', models.CharField(blank=True, max_length=300, null=True)),
                ('stars_gender', models.CharField(blank=True, max_length=300, null=True)),
                ('stars_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PloteKewords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plote_keywords', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pic', models.ImageField(blank=True, default='plceholder.png', null=True, upload_to="{% static 'images/")),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comment', models.TextField(max_length=250)),
                ('title', models.CharField(max_length=300)),
                ('rate', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moviedetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_detail', to='movieview.moviedetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_movie', to='movieview.user')),
            ],
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='stars',
            field=models.ManyToManyField(blank=True, null=True, to='movieview.MovieStars'),
        ),
    ]
