# Generated by Django 4.0.1 on 2022-01-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieview', '0002_alter_reviews_moviedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='moviedetail',
            new_name='movie_details',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='user_pic',
        ),
    ]
