# Generated by Django 4.0.1 on 2022-01-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieview', '0003_rename_moviedetail_reviews_movie_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='created_at',
            new_name='date',
        ),
    ]
