# Generated by Django 4.0.1 on 2022-01-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieview', '0004_rename_created_at_reviews_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
